name=C5 BF3901 Camera
version=1.0.0
author=Waveshare example port
maintainer=Waveshare
sentence=BF3901 SPI camera support for ESP32-C5-Touch-LCD-3.5.
paragraph=Precompiled for Arduino-ESP32 3.3.10 / ESP-IDF 5.5.4 on ESP32-C5.
category=Sensors
architectures=esp32
precompiled=true
ldflags=-lesp_cam_sensor -lesp_sccb_intf
